name: Python CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
      matrix:
        python-version: [3.8, 3.9, 3.11, 3.12, 3.13]

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Conda with Python ${{ matrix.python-version }}
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: ${{ matrix.python-version }}
        activate-environment: test-env
        
    - name: Install dependencies
      shell: bash -l {0}
      run: |
        conda install pip
        conda install path
        pip install -r requirements.txt
        pip install pytest
        
    - name: Run tests
      shell: bash -l {0}
      run: |
        pytest
